# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
jobs:
  iniciar-serico:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir mensagem
        run: echo "A mensagem sendo impressa"
      - name: imprimir segunda mensagem
        run: echo "a segunda mensagem está sendo impressa"
